---

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        input:
          destination: orders
          content-type: application/json      